name: Python script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run a Python script
        env:
          AWS_TOKEN: ${{ secrets.AWS_TOKEN }}
        run: python main.py
      - name: Python inline
        env:
          SALUDO: Hola desde github Actions
        shell: python
        run: |
          import os
          print("Saludos")
          print(os.environ['SALUDO'])
